/*
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/
#include <iostream>
#include <string>
#include <unordered_map>

using namespace std;

class Solution {
public:
	char findTheDifference(string s, string t) {
		unordered_map<char, int> sMap, tMap;

		for (const auto& c : s)
			sMap[c]++;

		for (const auto& c : t)
			tMap[c]++;

		for (const auto& p : tMap) {
			if (p.second != sMap[p.first])
				return p.first;
		}

		return 0;
	}
};

int main(int argc, char* argv[]) {
	Solution solution;

	cout << solution.findTheDifference("abcd", "abcde") << endl;

	cin.get();
	return 0;
}